name: QA Workflow

on:
  workflow_dispatch:
  pull_request:
    # Pull request events, only ready for review!
    types: [ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-format lcov gcovr cppcheck valgrind doxygen graphviz

      - name: Build project
        uses: ./.github/actions/building

